### ISSUE TITLE
We can't use the Canada wordmark instead of the gc sig in the upper left

### ISSUE THREAD

**Issue by patlaj** [gc-proto/design-refresh#12]
Will this be a more effective home link?

**Comment by pcwsmith** [comment]
hypothesis: Wordmark looks more like a logo that'd be clickable than the GC signature, thus more likely to be used as a back to home rescue. How to evaluate this?

**Comment by pcwsmith** [comment]
There's also the policy angle. Under FIP policy, the wordmark is considered as the main symbol of the GC.

However, confirmed with the Comms + FIP policy team that their rule is that on websites, the GC signature appears at the top and the wordmark appears at the bottom of the UI. Working on getting a rationale for that.

**Comment by pcwsmith** [comment]
See #21

**Comment by DK-TBS** [comment]
Hey @patlaj, did you get any useful intel from those tests you were running?  Last I heard we only had data from three participants, but I'm itching to know the answer to this one  :)

**Comment by patlaj** [comment]
Yep looks like the Wordmark is a much clearer home link than the GC signature. Details here:

https://docs.google.com/presentation/d/1okxBUPwVQm2I8Yo2ZusB-JJSqk950xm22QYILGe6nYQ/edit#slide=id.g3d8bf19af5_0_23

However - whether we should use it is another matter... there are other considerations.

**Comment by realredd** [comment]
I believe Canada wordmark would be an effective link, for the reasons mentioned above. It will also stabilize the user experience for those that have gone to many of the other country government sites. Most if not all of their pages use their identity (top left) as their home link. This real issue is, "how do we get the FIP people to update the policy"?
