### ISSUE TITLE
Basic Canada-wide demographic and usage stats acquired 

### ISSUE THREAD

**Issue by pcwsmith** [gc-proto/design-refresh#25]
items to cover:
- mobile and internet use among Canadians (have used cira.ca data in the past, from the annual Canadian Internet Factbook)
- Canada-wide literacy levels (Denise had tracked some of this down for us back in the day)
- high level demographic breakdowns - gender, education, first language (E, F, others)
- basic Canada.ca usage data - overall traffic, % mobile, etc.
- etc.

What we are looking for here is data points to demonstrate the at a high level the diversity of our audiences, and the impact of GC online

**Comment by pcwsmith** [comment]
some of theses data points have made it into our decks. Here's a few from my Innovation Fair presentation:

- Canada.ca domain: 1.2 million visits daily
- GC search engine: 200,000/day
- 100 top GC tasks: starting points 296 million annual visits

**Comment by ericcoops** [comment]
Canada-wide literacy levels
- 2012 Programme for the International Assessment of Adult Competencies
- 27,000 Canadians tested between ages 16 and 65
- Level 1 (functionally illiterate) - 17% of all Canadians, 21%  of people aged 45 to 65, 26% of people who weren't in the labour force, 27% of immigrants
- Level 3 (benchmark, minimum needed to function in today's society) - 48% of Canadians scored below this level

**Comment by ericcoops** [comment]
[The power of plain language - Writing for government (answers).pdf](https://github.com/gc-proto/design-refresh/files/2149881/The.power.of.plain.language.-.Writing.for.government.answers.pdf)

**Comment by ericcoops** [comment]
Mobile and internet use among Canadians

https://cira.ca/factbook/canadas-internet-factbook-2017 
- Nearly 90% of Canadians use the internet. (Source: ITU 2016)
- 71% of Canadians spend at least 3-4 hours on the internet each day
- **The use of a mobile device to access the internet has more than doubled since 2013. 2013: 32% | 2017: 67%**
- 46% of Canadian households have five or more internet-connected devices.
- 69% of Canadian internet users agree that Canadian organizations should use a .CA domain.
- Canada ranks 25th in the world on the International Telecommunications Union’s ICT Development Index (IDI 2016 Rank), which is based on internationally agreed information and communications technologies indicators including access, use and skills.

**Comment by ericcoops** [comment]
High level demographic breakdowns - gender, education, first language (E, F, others)

Eric here, let me start off by saying that I sincerely tried to get this data through StatsCan but **THEIR WEBSITE IS SO BAD I COULDN'T DO IT.** It's actually ridiculous, like they've never heard of user experience before. Just TRY to find a gender breakdown for Canada, I dare you! If you're like me you may end up on this page titled [2016 Census: Population trends in Canada by age and sex](https://www.statcan.gc.ca/eng/sc/video/2016census_agesex) but wait, all there is is a video talking about the census that DOESN'T MENTION SEX OR GENDER AT ALL. It is about how Canada's population is aging due to baby boomers, despite the very misleading title. I know StatsCan have fought tooth and nail to be separated from us, but their website sucks and it looks like Canada.ca. Is there nothing we can do?!

**Comment by ericcoops** [comment]
basic Canada.ca usage data - overall traffic, % mobile, etc.
Of the visits in last 12 months across Canada.ca

Overall traffic - https://sc5.omniture.com/x/5_6ioer
- Approx 360M visits 
- Consistent pattern of low visits on weekends followed by slight spike on Monday then lower plateau for rest of work week
- Significant drop in traffic from Dec 22 - Jan 3
- Significant spike on April 30 (income tax deadline)
- Jumps in baseline in last 12 months due to sites being migrated to Canada.ca

Device type - https://sc5.omniture.com/x/5_6iodd 
- 64.6% Non-mobile (Desktop or laptop)
- 29.5% Mobile phone (mostly Apple iPhone)
- 5.8% Tablet
- 0.1% Media player
- <0.1% for Gaming console, Television, set-top box, eReader

Time spent per visit - https://sc5.omniture.com/x/5_6iogd
- 41.0% less than 1 minute
- 26.5% 1-5 minutes
- 11.3% 5-10 minutes
- 16.0% 10-30 minutes
- 4.3% 30-60 minutes
- 0.9% >60 minutes

Referring domains with bounce rate - https://sc5.omniture.com/x/5_6iogk
- 33.8% Google.ca - 25.85% bounce
- 33.5% Typed/bookmarked  - 25.99% bounce
- 7.4% cra-arc.gc.ca - 8.12% bounce
- 6.9% cic.gc.ca - 19.92% bounce
- 4.1% Google.com - 30.73% bounce
- 2.8% Bing.com - 17.75% bounce
- 2.7% clegc-gckey.gc.ca - 13.67% bounce
- 1.6% securekeyconcierge.com - 13.64%
- 1.3% facebook.com - **61.25% bounce**

**Comment by pcwsmith** [comment]
When @ericcoops said he couldnt get stats can's data on gender breakdowns I couldn't help myself... I had to go looking. Managed to find this data table on Stats Can's site:

https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/prof/details/page.cfm?Lang=E&Geo1=PR&Code1=01&Geo2=&Code2=&Data=Count&SearchText=Canada&SearchType=Begins&SearchPR=01&B1=All&TABID=1 

Looks like according to the 2016 census, there were:

17,264,200 people who said they were male
17,887,530 people who said they were female
